project_id = "givergy"

[functions.get-products]
verify_jwt = false

[functions.calculate-shipping]
verify_jwt = false

[functions.get-address]
verify_jwt = false

[functions.create-order]
verify_jwt = false

[functions.generate-pdf]
verify_jwt = false