// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://olxrabdrzztvoqczfhyb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9seHJhYmRyenp0dm9xY3pmaHliIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM1NDQwMjgsImV4cCI6MjA2OTEyMDAyOH0.V8kb2xfUaIhpXeiK--O6XlLq8UBxDJw_MJtfdgGev0E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});